#!/bin/sh -e
#
# This script runs by default on startup.  First it starts the Jack audio
# server, and then it starts pd with a default patch.
#
# Feb. 2012, Edgar Berdahl
# Mod for SuperCollider April 2012, Florian Goltz

# Start up jack
/home/ccrma/bin/start-jackd
#jackd --silent -R -P62 -dalsa -dhw:0 -p512 -n3 -i2 -o2 -s -S -r44100 &


# Wait a few seconds for jackd to start
sleep 5

# Start up supercollider with example patch
# ----------------------------------------------------------
# Choose one from below.

sclang /home/ccrma/supercollider_demo/sc_standalone_example.scd  &

